// <auto-generated />
using System;
using ContactListWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactListWebApp.Data.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20260418234638_UpdateContactConstraints")]
    partial class UpdateContactConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactListWebApp.Models.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CustomSubcategory")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SubcategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7ae5234a-050b-45ff-8378-4704c9a9801c"),
                            CategoryId = 1,
                            DateOfBirth = new DateOnly(1990, 5, 15),
                            Email = "jan.kowalski@example.com",
                            Name = "Jan",
                            Password = "SecurePass123!+",
                            PhoneNumber = "+48123456789",
                            SubcategoryId = 1,
                            Surname = "Kowalski"
                        },
                        new
                        {
                            Id = new Guid("4f4e9f06-f15c-49ff-b7cb-31526bf19c1e"),
                            CategoryId = 2,
                            DateOfBirth = new DateOnly(1992, 3, 20),
                            Email = "maria.nowak@example.com",
                            Name = "Maria",
                            Password = "SecurePass456!*",
                            PhoneNumber = "+48987654321",
                            Surname = "Nowak"
                        },
                        new
                        {
                            Id = new Guid("25cd2c6c-e3c7-44da-9396-66b9b742406f"),
                            CategoryId = 3,
                            CustomSubcategory = "Driver",
                            DateOfBirth = new DateOnly(1988, 7, 10),
                            Email = "piotr.lewandowski@example.com",
                            Name = "Piotr",
                            Password = "SecurePass789!$",
                            PhoneNumber = "+48555666777",
                            Surname = "Lewandowski"
                        });
                });

            modelBuilder.Entity("ContactListWebApp.Models.Entities.ContactCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ContactCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Business"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Private"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Other"
                        });
                });

            modelBuilder.Entity("ContactListWebApp.Models.Entities.ContactSubcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubcategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContactCategoryId");

                    b.ToTable("ContactSubcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactCategoryId = 1,
                            SubcategoryName = "Boss"
                        },
                        new
                        {
                            Id = 2,
                            ContactCategoryId = 1,
                            SubcategoryName = "Client"
                        },
                        new
                        {
                            Id = 3,
                            ContactCategoryId = 1,
                            SubcategoryName = "Dealer"
                        },
                        new
                        {
                            Id = 4,
                            ContactCategoryId = 1,
                            SubcategoryName = "Partner"
                        },
                        new
                        {
                            Id = 5,
                            ContactCategoryId = 1,
                            SubcategoryName = "Manager"
                        });
                });

            modelBuilder.Entity("ContactListWebApp.Models.Entities.Contact", b =>
                {
                    b.HasOne("ContactListWebApp.Models.Entities.ContactCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContactListWebApp.Models.Entities.ContactSubcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId");

                    b.Navigation("Category");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("ContactListWebApp.Models.Entities.ContactSubcategory", b =>
                {
                    b.HasOne("ContactListWebApp.Models.Entities.ContactCategory", "ContactCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ContactCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactCategory");
                });

            modelBuilder.Entity("ContactListWebApp.Models.Entities.ContactCategory", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
